apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-binding
  namespace: travelo
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: travelo
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  namespace: travelo
subjects:
- kind: ServiceAccount
  name: readonly-user
  namespace: travelo
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io
