apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: travelo
data:
  SPRING_PROFILES_ACTIVE: default

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: travelo
  labels:
    app: travelo-backend
spec:
  selector:
    app: travelo-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment  
  namespace: travelo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travelo-backend
  template:
    metadata:
      labels:
        app: travelo-backend
    spec:
      containers:
        - name: backend
          image: lamsaafyassine/travelo-backend:139e0964dfe8cdb62e8182f7ef885e10cb26bf2b
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/travelo_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: CORS_ALLOWED_ORIGINS
              value: "http://localhost,http://localhost:8080,http://frontend.exam.local"
          readinessProbe:
            httpGet:
              path: /api/hello
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/hello
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /api/hello
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
