apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: travelo
spec:
  selector:
    app: travelo-frontend
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: travelo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travelo-frontend
  template:
    metadata:
      labels:
        app: travelo-frontend
    spec:
      containers:
        - name: frontend
          image: alaej/travelo-frontend:7ea490151e45b1ae7cabe876ea20f21b3ecb31e1
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://localhost
          ports:
            - containerPort: 3000
          # --- Probes ---
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
