apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: travelo-frontend-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: travelo-frontend
  namespaceSelector:
    matchNames:
      - travelo
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 25s
