apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: travelo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysql-exporter
          image: prom/mysqld-exporter:latest
          args:
            - "--mysqld.username=root"
            - "--mysqld.address=mysql:3306"
          ports:
            - containerPort: 9104
          env:
            - name: MYSQLD_EXPORTER_PASSWORD
              value: "yassine2004"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: travelo
  labels:
    app: mysql-exporter
spec:
  ports:
    - port: 9104
      targetPort: 9104
      name: metrics
  selector:
    app: mysql-exporter