apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: travelo-mysql-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mysql-exporter
  namespaceSelector:
    matchNames:
      - travelo
  endpoints:
    - port: metrics
      interval: 30s